import 'dart:convert';
import 'dart:typed_data';

import 'integration_config.dart';

class IntegrationTestVehicleData {
  final String licenseNumber;
  final String manufacturer;
  final String model;
  final int year;
  final int mileage;

  const IntegrationTestVehicleData({
    required this.licenseNumber,
    required this.manufacturer,
    required this.model,
    required this.year,
    required this.mileage,
  });
}

class IntegrationTestDataFactory {
  IntegrationTestDataFactory._();

  static int _vehicleCounter = 0;
  static int _fileCounter = 0;

  /// Creates an 8-digit vehicle number.
  ///
  /// Every call during the same test process returns a different number.
  static String createVehicleLicenseNumber() {
    _vehicleCounter++;

    final rawValue =
        DateTime.now().microsecondsSinceEpoch + _vehicleCounter;

    final eightDigitValue =
        10000000 + (rawValue % 90000000);

    return eightDigitValue.toString();
  }

  /// Default vehicle used by most integration tests.
  static IntegrationTestVehicleData createVehicle({
    String? licenseNumber,
    String manufacturer = 'Toyota',
    String model = 'Corolla',
    int year = 2022,
    int mileage = 60000,
  }) {
    return IntegrationTestVehicleData(
      licenseNumber:
          licenseNumber ?? createVehicleLicenseNumber(),
      manufacturer: manufacturer,
      model: model,
      year: year,
      mileage: mileage,
    );
  }

  /// Creates another vehicle that can be used for cross-vehicle RLS tests.
  static IntegrationTestVehicleData createSecondVehicle() {
    return IntegrationTestVehicleData(
      licenseNumber: createVehicleLicenseNumber(),
      manufacturer: 'Honda',
      model: 'Civic',
      year: 2021,
      mileage: 45000,
    );
  }

  /// Generates a unique identifier for temporary test data.
  static String uniqueToken([String prefix = 'test']) {
    return '${prefix}_${IntegrationConfig.runId}_'
        '${DateTime.now().microsecondsSinceEpoch}';
  }

  /// Generates a unique file name for Storage tests.
  static String uniqueFileName({
    String prefix = 'carkeep_integration',
    String extension = 'txt',
  }) {
    _fileCounter++;

    return '${prefix}_${IntegrationConfig.runId}_'
        '${DateTime.now().microsecondsSinceEpoch}_'
        '$_fileCounter.$extension';
  }

  /// Small deterministic file payload for Storage upload/download tests.
  ///
  /// We use generated bytes instead of a real personal document.
  static Uint8List createTestFileBytes({
    String content = 'CarKeep integration test document',
  }) {
    final text = '$content\n'
        'Run: ${IntegrationConfig.runId}\n'
        'Generated: ${DateTime.now().toIso8601String()}';

    return Uint8List.fromList(
      utf8.encode(text),
    );
  }

  static DateTime date2027August31() {
    return DateTime(2027, 8, 31);
  }

  static DateTime date2028August31() {
    return DateTime(2028, 8, 31);
  }

  static DateTime serviceDate2026August30() {
    return DateTime(2026, 8, 30);
  }

  static DateTime serviceDate2027March1() {
    return DateTime(2027, 3, 1);
  }
}